# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    webcamStat = False
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 499)
        MainWindow.setMinimumSize(QtCore.QSize(877, 499))
        MainWindow.setMaximumSize(QtCore.QSize(877, 499))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgba(250,250,250,255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.appTitle = QtWidgets.QLabel(self.centralwidget)
        self.appTitle.setGeometry(QtCore.QRect(90, 10, 691, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.appTitle.setFont(font)
        self.appTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.appTitle.setStyleSheet("text-align:center;\n"
"background:rgba(0,0,0,0);")
        self.appTitle.setTextFormat(QtCore.Qt.AutoText)
        self.appTitle.setObjectName("appTitle")
        self.titleLine = QtWidgets.QFrame(self.centralwidget)
        self.titleLine.setGeometry(QtCore.QRect(-10, 90, 891, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.titleLine.sizePolicy().hasHeightForWidth())
        self.titleLine.setSizePolicy(sizePolicy)
        self.titleLine.setMinimumSize(QtCore.QSize(0, 5))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.titleLine.setPalette(palette)
        self.titleLine.setStyleSheet("background: rgba(0,0,0,0);")
        self.titleLine.setLineWidth(0)
        self.titleLine.setMidLineWidth(5)
        self.titleLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.titleLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.titleLine.setObjectName("titleLine")
        self.testImageBorder = QtWidgets.QGraphicsView(self.centralwidget)
        self.testImageBorder.setGeometry(QtCore.QRect(270, 170, 251, 251))
        self.testImageBorder.setObjectName("testImageBorder")
        self.closestImageBorder = QtWidgets.QGraphicsView(self.centralwidget)
        self.closestImageBorder.setGeometry(QtCore.QRect(570, 170, 251, 251))
        self.closestImageBorder.setObjectName("closestImageBorder")
        self.testLabel = QtWidgets.QLabel(self.centralwidget)
        self.testLabel.setGeometry(QtCore.QRect(270, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.testLabel.setFont(font)
        self.testLabel.setObjectName("testLabel")
        self.closestLabel = QtWidgets.QLabel(self.centralwidget)
        self.closestLabel.setGeometry(QtCore.QRect(570, 130, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.closestLabel.setFont(font)
        self.closestLabel.setObjectName("closestLabel")
        self.datasetLabel = QtWidgets.QLabel(self.centralwidget)
        self.datasetLabel.setGeometry(QtCore.QRect(20, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.datasetLabel.setFont(font)
        self.datasetLabel.setObjectName("datasetLabel")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(20, 260, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.imageLabel.setFont(font)
        self.imageLabel.setStyleSheet("background:rgba(0,0,0,0);")
        self.imageLabel.setObjectName("imageLabel")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setGeometry(QtCore.QRect(20, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.fileButton.setFont(font)
        self.fileButton.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius:10px;\n"
"background: rgba(0,0,0,0);\n"
"border-color: #2196F3;\n"
"color: dodgerblue;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #2196F3;\n"
"color:white;\n"
"}")
        self.fileButton.setIconSize(QtCore.QSize(16, 16))
        self.fileButton.setObjectName("fileButton")
        self.fileButton.clicked.connect(self.getFile)
        self.folderButton = QtWidgets.QPushButton(self.centralwidget)
        self.folderButton.setGeometry(QtCore.QRect(20, 190, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.folderButton.setFont(font)
        self.folderButton.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius:10px;\n"
"background: rgba(0,0,0,0);\n"
"border-color: #2196F3;\n"
"color: dodgerblue;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #2196F3;\n"
"color:white;\n"
"}")
        self.folderButton.setIconSize(QtCore.QSize(16, 16))
        self.folderButton.setAutoDefault(False)
        self.folderButton.setDefault(False)
        self.folderButton.setFlat(False)
        self.folderButton.setObjectName("folderButton")
        self.webcamButton = QtWidgets.QPushButton(self.centralwidget)
        self.webcamButton.setGeometry(QtCore.QRect(20, 330, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.webcamButton.setFont(font)
        self.webcamButton.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius:10px;\n"
"background: rgba(0,0,0,0);\n"
"border-color: #2196F3;\n"
"color: dodgerblue;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #2196F3;\n"
"color:white;\n"
"}")
        self.webcamButton.setIconSize(QtCore.QSize(16, 16))
        self.webcamButton.setObjectName("webcamButton")
        self.webcamButton.clicked.connect(self.toggleWebcam)
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(20, 370, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.resultLabel.setFont(font)
        self.resultLabel.setStyleSheet("background:rgba(0,0,0,0);")
        self.resultLabel.setObjectName("resultLabel")
        self.execTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.execTimeLabel.setGeometry(QtCore.QRect(270, 440, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.execTimeLabel.setFont(font)
        self.execTimeLabel.setStyleSheet("background:rgba(0,0,0,0);")
        self.execTimeLabel.setObjectName("execTimeLabel")
        self.matchLabel = QtWidgets.QLabel(self.centralwidget)
        self.matchLabel.setGeometry(QtCore.QRect(20, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.matchLabel.setFont(font)
        self.matchLabel.setStyleSheet("background:rgba(0,0,0,0);")
        self.matchLabel.setText("")
        self.matchLabel.setObjectName("matchLabel")
        self.execTime = QtWidgets.QLabel(self.centralwidget)
        self.execTime.setGeometry(QtCore.QRect(430, 440, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.execTime.setFont(font)
        self.execTime.setStyleSheet("background:rgba(0,0,0,0);")
        self.execTime.setText("")
        self.execTime.setObjectName("execTime")
        self.trainingTime = QtWidgets.QLabel(self.centralwidget)
        self.trainingTime.setGeometry(QtCore.QRect(20, 230, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.trainingTime.setFont(font)
        self.trainingTime.setStyleSheet("background:rgba(0,0,0,0);")
        self.trainingTime.setText("")
        self.trainingTime.setObjectName("trainingTime")
        self.testImage = QtWidgets.QLabel(self.centralwidget)
        self.testImage.setGeometry(QtCore.QRect(270, 170, 251, 251))
        self.testImage.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.testImage.setText("")
        self.testImage.setObjectName("testImage")
        self.closestImage = QtWidgets.QLabel(self.centralwidget)
        self.closestImage.setGeometry(QtCore.QRect(570, 170, 251, 251))
        self.closestImage.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.closestImage.setText("")
        self.closestImage.setObjectName("closestImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.folderButton, self.closestImageBorder)
        MainWindow.setTabOrder(self.closestImageBorder, self.fileButton)
        MainWindow.setTabOrder(self.fileButton, self.testImageBorder)
        MainWindow.setTabOrder(self.testImageBorder, self.webcamButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appTitle.setText(_translate("MainWindow", "Face Recognition BPJS"))
        self.testLabel.setText(_translate("MainWindow", "Test Image"))
        self.closestLabel.setText(_translate("MainWindow", "Closest Image"))
        self.datasetLabel.setText(_translate("MainWindow", "Insert Your Dataset"))
        self.imageLabel.setText(_translate("MainWindow", "Insert Your Image"))
        self.fileButton.setText(_translate("MainWindow", "Choose File"))
        self.folderButton.setText(_translate("MainWindow", "Choose Folder"))
        self.webcamButton.setText(_translate("MainWindow", "WebCam"))
        self.resultLabel.setText(_translate("MainWindow", "Result"))
        self.execTimeLabel.setText(_translate("MainWindow", "Execution Time:"))

    def getFile(self):
        self.file = QtWidgets.QFileDialog.getOpenFileName()
        self.testImage.setText(self.file[0])
        self.testImage.setPixmap(QtGui.QPixmap(self.file[0]))
        self.testImage.setScaledContents(True)
    
    def toggleWebcam(self):
        if self.webcamStat:
            self.webcamStat = False
            self.testImage.clear()
            self.webcam.stop()
        else:
            self.webcamStat = True
            self.webcam = Webcam()
            self.webcam.start()
            self.webcam.ImageUpdate.connect(self.updateImage)
    
    def updateImage(self, Image):
        self.testImage.setPixmap(QtGui.QPixmap.fromImage(Image))
        self.testImage.setScaledContents(True)

class Webcam(QtCore.QThread):
    ImageUpdate = QtCore.pyqtSignal(QtGui.QImage)
    def run(self):
        self.ThreadActive = True
        Capture = cv2.VideoCapture(0)
        while self.ThreadActive:
            ret, frame = Capture.read()
            if ret:
                Image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                FlippedImage = cv2.flip(Image, 1)
                ConvertToQtFormat = QtGui.QImage(FlippedImage.data, FlippedImage.shape[1], FlippedImage.shape[0], QtGui.QImage.Format_RGB888)
                Pic = ConvertToQtFormat.scaled(640, 480, QtCore.Qt.KeepAspectRatio)
                self.ImageUpdate.emit(Pic)
    def stop(self):
        self.ThreadActive = False
        self.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
